name: Generate Snake Animation

on:
  schedule:
    # Update snake animation setiap hari
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Jalankan Snake Animation Generator
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          # Jalankan script untuk meng-generate SVG
          github_user_name: rigelra15
          outputs: dist/snake.svg

      # Commit hasilnya ke branch `output`
      - name: Push Snake Animation to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
